### ISSUE TITLE
Missing patternlab server

### ISSUE THREAD

**Issue by gablittledevshop** [forumone/gesso-theme-wordpress#106]
Hi, I have a feature request.  I think it would be helpful to have a grunt task that spins up the patternlab local environment and refresh the page when changes are made.  Currently, the `grunt` task does watch for changes, but you have to manually spin up a patternlab server and it doesn't refresh when changes are made.

**Comment by coreylafferty** [comment]
@gablittledevshop it'd be pretty simple to add the --server flag into the `shell.js` patternlab task, but I'm not sure that the server and a watch can be running from the same task since running the server seems to freeze things until it's stopped.  

Regardless, a bigger issue is that using the Pattern Lab server doesn't really work with how we've configured Gesso and envisioned it being used -- since we're using Pattern Lab to only serve up markup and share the exact same CSS/JS/image assets as the theme, all of the images, CSS and JS files are in folders below the `pattern-lab/public/` folder, so when the server is running at localhost, it will try to access files it can't find.  For example, Pattern Lab looks for `"../../../css/styles.css"` which is at a lower level outside the `/gesso/pattern-lab/public` folder at /gesso/css/styles.css, which can't be found when Pattern Lab is being served from localhost since nothing below the pattern-lab/public/ folder is accessible to it.  

If you have a workaround for that limitation please let me know, but our approach generally is to do one of the following:

1. Open the main Pattern Lab index file directly in the browser from the native file system.  Example: `file:///C:/websites/mysite/wp-content/themes/gesso/pattern-lab/public/index.html`
2. Serve the WordPress site locally (using MAMP, Vagrant, Docker, etc.) and access Pattern Lab through that server (e.g., [http://localhost:8080/wp-content/themes/gesso/pattern-lab/public/index.html](http://localhost:8080/wp-content/themes/gesso/pattern-lab/public/index.html))

**Comment by gablittledevshop** [comment]
@coreylafferty your suggestion will work.  I tried spinning up the server with the php command per the documentation, but it doesn't seem to refresh the page when changes are made, probably browsersync would need to be incorporated somehow.  Also, I had to symlink the assets to make it available, so it's a bit more work to get the same result that you suggested.  I find it helpful to work directly in patternlab to build out the styleguide and do rapid prototyping of the pages, and most other themes (albeit non-wordpress themes) are able to spin up the patternlab server and auto refresh the page on changes.

In anycase, this will still work.

Thanks!
