### ISSUE TITLE
Timber version above 1.9.4 causes white screen of death

### ISSUE THREAD

**Issue by yumyo** [forumone/gesso-theme-wordpress#110]
Hi all,
I have developed a theme with Gesso two years ago, keeping it regularly updated until the present. Just few days ago, after updating WP to 5.2.2 along with some plugin (ACF, Query Monitor) I ended up facing a white screen of death. (WP_DEBUG true, but no errors displayed or logged). 
I have deactivated each and every plugin except Timber and ACF since the theme heavily relies on the latter too. I was then able to isolate the issue at theme level, and specifically at the call `{{ function('get_header') }}` within **base.twig**

By the time being, I am just commenting the function call but I would really be happy to understand what changed and why to avoid further, unexpected issues. 

Thanks in advance for any help.

**Comment by alecherryy** [comment]
Hello @yumyo!

did you update Timber as well? There's a bug in the newest version. See the two issues from the Timber repo below. To get things working until a new version is released you can use the test version Jared links to in both of the issues or downgrade to version 1.9.4. Let me know if that works. Thanks!

https://github.com/timber/timber/issues/2016
https://github.com/timber/timber/issues/2020

**Comment by cssgirl** [comment]
@coreylafferty it looks like this issue and #105 are caused by the same Timber issues. Keeping the version at 1.9.4 is the current working fix. 

Should we close these two issues and make a note in the README that until further notice that Timber shouldn't be updated past 1.9.4?

I just rechecked with 1.10.0 and still get a WSOD on a base install.

**Comment by kreonal** [comment]
Ran into this issue on a site with Gesso 2.0. Tried updating to 1.12.0, but the front-end wouldn't render (WSOD).

**Comment by coreylafferty** [comment]
@kreonal I just did some testing, and you're correct.  Gesso 2.0 still does not work with the newer versions of Timber (I believe due to a conflict between the Twig version in Timber and another dependency, likely related to the PHP version of Pattern Lab).  

However, the newer versions of Gesso (e.g., what's on the 3.x branch / release 3.2) do not have this issue and worked fine with Timber 1.12.0 in my testing.  I suspect this is because Gesso 3 uses the NodeJS version of Pattern Lab vs the older PHP version.
  
I would recommend either downgrading Timber to version 1.9.4 if using Gesso 2 or upgrading to Gesso 3.

We're no longer in active development on Gesso 2, but I've added a note to the 2.x branch README indicating the Timber version issue.

**Comment by coreylafferty** [comment]
@kreonal I did some further testing and deleted my prior comment as it was inaccurate.  Depending on how you're running WordPress, it looks like the newer versions of Timber can cause problems with Gesso.  This might be related to a bug in Timber when WP_DEBUG is disabled or not set, detailed here: https://github.com/timber/timber/issues/2084

Until there's a definite fix, if you're having issues I'd recommend e downgrading to Timber version 1.9.4 or enabling WP_DEBUG.

**Comment by alleyhector** [comment]
I think something similar is happening to me with Timber 1.9.4 when trying to edit pages/posts as well. I also did a totally new installation I tried on my localhost with the more recent versions and it has the white screen of death on the front end as well as the admin. 

But anyway, the versions I'm working on fixing for a live site are:

Wordpress 5.2.4
Timber 1.9.4
Gesso 2.0
ACF Pro 5.8.6

Any updates/ideas on this?

**Comment by houblon** [comment]
@coreylafferty It appears that, for out-of-the-box Gesso, the lack of a call to `get_footer()` is the issue. In _base.twig_ there's `{{ function('get_header') }}`, but the footer block only contains `{{ function('wp_footer') }}`. Adding `{{ function('get_footer') }}` to _base.twig_ solves the problem because _footer.php_ assigns the output buffer contents to the context and ends the buffer. Also, the comments in _footer.php_ reference `wp_footer()` when they should reference `get_footer()`. Likewise with _header.php_ referencing `wp_head()` instead of `get_header()`.

Maybe it would be useful to add something about this to the README so folks can add/remove the buffer functionality as needed.

**Comment by coreylafferty** [comment]
@houblon thank you for the detailed information!  Based on your explanation, I've created a PR that I think addresses the issue and solves the WSOD problem.  If you have any thoughts on the changes, please leave a comment here or in the PR.  Thanks again!

https://github.com/forumone/gesso-wp/pull/227

**Comment by houblon** [comment]
@coreylafferty Very glad this is useful and happy to help! There's one little thing which I'll put in the PR, but your changes look great. Cheers!
